name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Copy repository contents via scp
        uses: appleboy/scp-action@master
        env:
          HOST: ${{ secrets.DEPLOY_HOST }}
          USERNAME: ${{ secrets.DEPLOY_USERNAME }}
          PORT: 22
          KEY: ${{ secrets.DEPLOY_PRIVATE_KEY }}
        with:
          source: "."
          target: "/home/georgievsky/bind"

      - name: Write .env file
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          USERNAME: ${{ secrets.DEPLOY_USERNAME }}
          PORT: 22
          KEY: ${{ secrets.DEPLOY_PRIVATE_KEY }}
          script: echo -e "${{ secrets.DEPLOY_ENV }}" > /home/georgievsky/bind/server/.env

      - name: Install dependencies
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          USERNAME: ${{ secrets.DEPLOY_USERNAME }}
          PORT: 22
          KEY: ${{ secrets.DEPLOY_PRIVATE_KEY }}
          script: cd /home/georgievsky/bind && yarn i

      - name: Install dependencies
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          USERNAME: ${{ secrets.DEPLOY_USERNAME }}
          PORT: 22
          KEY: ${{ secrets.DEPLOY_PRIVATE_KEY }}
          script: cd /home/georgievsky/bind && yarn i