name: Deploy

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Copy repository contents via scp
        uses: appleboy/scp-action@master
        env:
          HOST: ${{ secrets.DEPLOY_HOST }}
          USERNAME: ${{ secrets.DEPLOY_USERNAME }}
          PORT: 22
          KEY: ${{ secrets.DEPLOY_PRIVATE_KEY }}
        with:
          source: "."
          target: "/home/georgievsky/bind"

      - name: Executing remote command
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          USERNAME: ${{ secrets.DEPLOY_USERNAME }}
          PORT: 22
          KEY: ${{ secrets.DEPLOY_PRIVATE_KEY }}
          script: echo Hello world!